INSERT INTO public.courses (name) VALUES ('Python');
INSERT INTO public.courses (name) VALUES ('Java');
INSERT INTO public.courses (name) VALUES ('PHP');
INSERT INTO public.groups(name, course_id) VALUES ('nix-4', 2);
INSERT INTO public.groups(name, course_id) VALUES ('alevel-1', 1);
INSERT INTO public.groups(name, course_id) VALUES ('nix-5', 2);
INSERT INTO public.groups(name, course_id) VALUES ('alevel-2', 3);
INSERT INTO public.groups(name, course_id) VALUES ('nix-1', 1);
INSERT INTO public.groups(name, course_id) VALUES ('nix-3', 3);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-04-30 10:00:00', 'Quorum blockchain', 7, 2);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-05-15 12:45:00', 'Reading Data CSV and TXT', 8, 1);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-06-17 10:00:00', 'Hibernate Mapping', 3, 2);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-05-16 13:00:00', 'World Wide Web Communication', 2, 3);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-06-13 19:00:00', 'What is Docker?', 6, 1);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-04-13 09:00:00', 'Need of Blockchain', 7, 2);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-05-10 17:00:00', 'New classes in java.time', 1, 2);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-06-06 17:00:00', 'Hibernate ORM', 3, 2);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-05-31 14:30:00', 'XML Http Request', 2, 3);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-05-26 12:45:00', 'Reading Data from Databases', 8, 1);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-05-04 14:00:00', 'New Date/ Time API', 1, 2);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-04-17 16:30:00', 'OOPs Concepts', 4, 2);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-06-28 19:30:00', 'PDO_MYSQL', 5, 3);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-06-17 16:30:00', 'Why do we need Docker?', 6, 1);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-04-01 16:00:00', 'What are Classes and Objects?', 4, 2);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-06-19 18:00:00', 'MySQL Improved', 5, 3);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-06-01 09:00:00', 'Final exam', 9, 2);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-06-01 09:00:00', 'Final exam', 10, 3);
INSERT INTO public.lessons(date_time, name, topic_id, course_id) VALUES ('2021-06-01 09:00:00', 'Final exam', 11, 1);
INSERT INTO public.marks(point, lesson_id, student_id, group_id) VALUES (7, 17, 1, 1);
INSERT INTO public.marks(point, lesson_id, student_id, group_id) VALUES (1, 18, 10, 4);
INSERT INTO public.marks(point, lesson_id, student_id, group_id) VALUES (4, 19, 12, 2);
INSERT INTO public.marks(point, lesson_id, student_id, group_id) VALUES (9, 18, 7, 4);
INSERT INTO public.marks(point, lesson_id, student_id, group_id) VALUES (10, 18, 5, 6);
INSERT INTO public.marks(point, lesson_id, student_id, group_id) VALUES (6, 19, 11, 5);
INSERT INTO public.marks(point, lesson_id, student_id, group_id) VALUES (10, 17, 15, 1);
INSERT INTO public.marks(point, lesson_id, student_id, group_id) VALUES (8, 18, 14, 6);
INSERT INTO public.marks(point, lesson_id, student_id, group_id) VALUES (7, 17, 6, 1);
INSERT INTO public.marks(point, lesson_id, student_id, group_id) VALUES (6, 17, 9, 3);
INSERT INTO public.marks(point, lesson_id, student_id, group_id) VALUES (8, 17, 4, 1);
INSERT INTO public.marks(point, lesson_id, student_id, group_id) VALUES (10, 18, 3, 4);
INSERT INTO public.marks(point, lesson_id, student_id, group_id) VALUES (3, 19, 2, 2);
INSERT INTO public.marks(point, lesson_id, student_id, group_id) VALUES (9, 19, 13, 5);
INSERT INTO public.students(age, email, first_name, last_name, group_id) VALUES (19, 'sofiahalamai@gmail.com', 'Sofia', 'Halamai', 1);
INSERT INTO public.students(age, email, first_name, last_name, group_id) VALUES (35, 'jamesgate@gmail.com', 'James', 'Gate', 2);
INSERT INTO public.students(age, email, first_name, last_name, group_id) VALUES (18, 'kellygood@gmail.com', 'Kelly', 'Goodman', 4);
INSERT INTO public.students(age, email, first_name, last_name, group_id) VALUES (20, 'ivancourse@gmail.com', 'Ivan', 'Harrison', 1);
INSERT INTO public.students(age, email, first_name, last_name, group_id) VALUES (20, 'lucfros@gmail.com', 'Lucy', 'Dutton', 6);
INSERT INTO public.students(age, email, first_name, last_name, group_id) VALUES (18, 'olivka@gmail.com', 'Olivia', 'Little', 1);
INSERT INTO public.students(age, email, first_name, last_name, group_id) VALUES (22, 'dysonkl@gmail.com', 'Alice', 'Dyson', 4);
INSERT INTO public.students(age, email, first_name, last_name, group_id) VALUES (26, 'lewinal@gmail.com', 'Alex', 'Lewin', 5);
INSERT INTO public.students(age, email, first_name, last_name, group_id) VALUES (21, 'emmas@gmail.com', 'Emma', 'Otis', 3);
INSERT INTO public.students(age, email, first_name, last_name, group_id) VALUES (19, 'breadfred@gmail.com', 'Fred', 'Holiday', 4);
INSERT INTO public.students(age, email, first_name, last_name, group_id) VALUES (29, 'failed@gmail.com', 'Ben', 'Adrian', 5);
INSERT INTO public.students(age, email, first_name, last_name, group_id) VALUES (19, 'goodday@gmail.com', 'Andrew', 'Day', 2);
INSERT INTO public.students(age, email, first_name, last_name, group_id) VALUES (24, 'jug@gmail.com', 'Bill', 'Keat', 5);
INSERT INTO public.students(age, email, first_name, last_name, group_id) VALUES (18, 'kendaltest@gmail.com', 'Tom', 'Kendal', 6);
INSERT INTO public.students(age, email, first_name, last_name, group_id) VALUES (23, 'victsec@gmail.com', 'Victoria', 'Secret', 1);
INSERT INTO public.teachers(email, first_name, last_name, course_id) VALUES ('egorfuntusov@gmail.com', 'Egor', 'Funtusov', 2);
INSERT INTO public.teachers(email, first_name, last_name, course_id) VALUES ('voidaspect@gmail.com', 'Mikhail', 'Gorbunov', 2);
INSERT INTO public.teachers(email, first_name, last_name, course_id) VALUES ('phpteacher@gmail.com', 'Ivan', 'Ivanov', 3);
INSERT INTO public.teachers(email, first_name, last_name, course_id) VALUES ('pythondeveloper1gmail.com', 'Dima', 'Goy', 1);
INSERT INTO public.teachers(email, first_name, last_name, course_id) VALUES ('sergptu@gmail.com', 'Sergey', 'Ptushkin', 1);
INSERT INTO public.teachers(email, first_name, last_name, course_id) VALUES ('sidorov@gmail.com', 'Artem', 'Sidorov', 3);
INSERT INTO public.topics(name, course_id, teacher_id) VALUES ('Data API', 2, 1);
INSERT INTO public.topics(name, course_id, teacher_id) VALUES ('HTTP Protocol', 3, 3);
INSERT INTO public.topics(name, course_id, teacher_id) VALUES ('Hibernate', 2, 2);
INSERT INTO public.topics(name, course_id, teacher_id) VALUES ('OOP', 2, 1);
INSERT INTO public.topics(name, course_id, teacher_id) VALUES ('MySql', 3, 6);
INSERT INTO public.topics(name, course_id, teacher_id) VALUES ('Docker', 1, 4);
INSERT INTO public.topics(name, course_id, teacher_id) VALUES ('Blockchain', 2, 1);
INSERT INTO public.topics(name, course_id, teacher_id) VALUES ('Data Analysis', 1, 5);
INSERT INTO public.topics(name, course_id, teacher_id) VALUES ('Exam Java', 2, 1);
INSERT INTO public.topics(name, course_id, teacher_id) VALUES ('Exam PHP', 3, 3);
INSERT INTO public.topics(name, course_id, teacher_id) VALUES ('Exam Python', 1, 5);